name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      # Optional: Ensure ESLint is installed if it's missing from the project
      - name: Install ESLint
        run: npm install eslint --save-dev
        if: failure()

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
