name: Custom Workflow

on:
  push:
    branches:
      - custom-workflow

jobs:
  custom-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print current directory
        run: pwd

      - name: List files in directory
        run: ls -al
