name: Generate Release Notes

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5

      - name: Publish Release Notes
        run: echo "Release notes generated and published successfully"
