name: Scheduled Tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 03:00 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
